In [4]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [5]:
 df=pd.read_csv('Cars.csv')

# Data Preprocessing

In [6]:
df.head()

model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0    A1  2017  12500       Manual    15735   Petrol  150  55.4         1.4
1    A6  2016  16500    Automatic    36203   Diesel   20  64.2         2.0
2    A1  2016  11000       Manual    29946   Petrol   30  55.4         1.4
3    A4  2017  16800    Automatic    25952   Diesel  145  67.3         2.0
4    A3  2019  17300       Manual     1998   Petrol  145  49.6         1.0

In [7]:
X=df.drop('price', axis=1)
Y=df['price']

In [8]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
le2= LabelEncoder()

In [9]:
X['model']=le.fit_transform(X['model'])

In [10]:
X['fuelType']=le2.fit_transform(X['fuelType'])

In [11]:
X.head()

model  year transmission  mileage  fuelType  tax   mpg  engineSize
0      0  2017       Manual    15735         2  150  55.4         1.4
1      5  2016    Automatic    36203         0   20  64.2         2.0
2      0  2016       Manual    29946         2   30  55.4         1.4
3      3  2017    Automatic    25952         0  145  67.3         2.0
4      2  2019       Manual     1998         2  145  49.6         1.0

In [12]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder(),[2])],remainder='passthrough')
X = ct.fit_transform(X)

In [61]:
X

array([[-0.58326752,  1.2007284 , -0.71233307, ...,  0.35714729,
         0.35755001, -0.88021837],
       [ 1.71447913, -0.83282781, -0.71233307, ..., -1.57832278,
         1.03713001,  0.11492465],
       [-0.58326752,  1.2007284 , -0.71233307, ..., -1.42944047,
         0.35755001, -0.88021837],
       ...,
       [-0.58326752,  1.2007284 , -0.71233307, ...,  0.35714729,
        -0.09035499, -1.54364705],
       [ 1.71447913, -0.83282781, -0.71233307, ...,  0.35714729,
        -0.22163749, -0.88021837],
       [-0.58326752,  1.2007284 , -0.71233307, ...,  0.35714729,
        -0.22163749, -0.88021837]])

# Fearure Scaling

In [59]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [60]:
X

array([[-0.58326752,  1.2007284 , -0.71233307, ...,  0.35714729,
         0.35755001, -0.88021837],
       [ 1.71447913, -0.83282781, -0.71233307, ..., -1.57832278,
         1.03713001,  0.11492465],
       [-0.58326752,  1.2007284 , -0.71233307, ..., -1.42944047,
         0.35755001, -0.88021837],
       ...,
       [-0.58326752,  1.2007284 , -0.71233307, ...,  0.35714729,
        -0.09035499, -1.54364705],
       [ 1.71447913, -0.83282781, -0.71233307, ...,  0.35714729,
        -0.22163749, -0.88021837],
       [-0.58326752,  1.2007284 , -0.71233307, ...,  0.35714729,
        -0.22163749, -0.88021837]])

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
X_train, X_test, y_train, y_test = train_test_split(
    X, Y, test_size=0.2, random_state=42)

In [19]:
from sklearn.ensemble import RandomForestRegressor
model=RandomForestRegressor(random_state=0)
model.fit(X_train,y_train)

RandomForestRegressor(random_state=0)

# Trainig Result

In [20]:
y_prediction=model.predict(X_test)

In [22]:
print(y_prediction)

[ 9466.01   20491.66   29868.2625 ... 16509.14   20505.     10496.89  ]


In [27]:
print(y_test)

10442     9990
2907     22382
7388     28990
3016     30777
7890     14950
         ...  
8606     31450
8977     12900
3673     16750
1034     21996
6867      9547
Name: price, Length: 2134, dtype: int64


# Accuracy

In [25]:
from sklearn.metrics import r2_score
r2_score(y_test,y_prediction)

0.962637634035639

In [39]:
X_test

array([[-0.58326752,  1.2007284 , -0.71233307, ..., -1.42944047,
         0.92901501,  0.11492465],
       [-0.58326752,  1.2007284 , -0.71233307, ...,  0.28270613,
         0.04865001, -0.54850403],
       [-0.58326752, -0.83282781,  1.40383768, ...,  0.35714729,
        -0.22163749,  0.11492465],
       ...,
       [-0.58326752, -0.83282781,  1.40383768, ..., -1.42944047,
         1.03713001,  0.11492465],
       [-0.58326752,  1.2007284 , -0.71233307, ...,  0.28270613,
         0.04865001, -0.54850403],
       [-0.58326752,  1.2007284 , -0.71233307, ..., -1.57832278,
         1.2765275 ,  0.11492465]])

In [45]:
# Example input data (as it would appear after transformations such as encoding and scaling)
# The example assumes these are the values after OneHotEncoding, StandardScaling, etc.
input_data = np.array([0, 1, 0,1,2017,0,0 ,150, 55.4, 1.4])

# Reshape the input data to match the model's expected input format (1 sample, N features)
reshaped_input = input_data.reshape(1, -1)

# Make a prediction using the trained model
prediction = model.predict(reshaped_input)

# Output the predicted price
print(f"The predicted price of the car is: {prediction[0]}")


The predicted price of the car is: 28018.12
